// GENERATED by analysis/build_spec.py -- do not edit by hand.
// Parameter table measured from the original SwarmSynth.dll: names and
// units come from the plugin itself, the quantiser and display laws were
// fitted to its own readback with zero residual error.
#pragma once
#include <cstdint>

namespace swarm {

enum class Quant { Pct, Pan, Count, Ms1k, Semi, Pct50, Real };
enum class Disp  { Pct, Db, Pan, Count, Ms1k, Semi, Pct50, Time, Seed };

struct ParamSpec {
    int         index;
    const char* id;
    const char* name;
    const char* unit;
    Quant       quant;
    Disp        disp;
    int         chunkOffset;   // byte offset in an original .swarm chunk
    bool        chunkIsFloat;
};

inline constexpr int kNumParams = 101;

inline constexpr ParamSpec kParams[kNumParams] = {
    {   0, "volume", "Volume", "dB", Quant::Pct, Disp::Db, 24, false },
    {   1, "pan", "Pan", "", Quant::Pan, Disp::Pan, 36, false },
    {   2, "resonance", "Resonance", "", Quant::Pct, Disp::Pct, 40, false },
    {   3, "noise", "Noise", "%", Quant::Pct, Disp::Pct, 44, false },
    {   4, "vol_var", "Vol Var.", "%", Quant::Pct, Disp::Pct, 48, false },
    {   5, "pitch_var", "Pitch Var.", "%", Quant::Pct, Disp::Pct, 52, false },
    {   6, "pan_var", "Pan Var.", "%", Quant::Pct, Disp::Pct, 56, false },
    {   7, "res_var", "Res Var.", "%", Quant::Pct, Disp::Pct, 60, false },
    {   8, "noise_var", "Noise Var.", "%", Quant::Pct, Disp::Pct, 64, false },
    {   9, "speed", "Speed", "%", Quant::Pct, Disp::Pct, 80, false },
    {  10, "speed_lfo", "Speed LFO", "%", Quant::Pct, Disp::Pct, 1888, false },
    {  11, "std_dev", "Std. Dev.", "%", Quant::Pct, Disp::Pct, 84, false },
    {  12, "reflection", "Reflection", "%", Quant::Pct, Disp::Pct, 88, false },
    {  13, "attract", "Attract", "", Quant::Pct, Disp::Pct, 92, false },
    {  14, "repel", "Repel", "", Quant::Pct, Disp::Pct, 96, false },
    {  15, "proximity", "Proximity", "", Quant::Pct, Disp::Pct, 100, false },
    {  16, "lowpass", "Lowpass", "", Quant::Pct, Disp::Pct, 72, false },
    {  17, "q", "'Q'", "", Quant::Pct, Disp::Pct, 68, false },
    {  18, "overdrive", "Overdrive", "", Quant::Pct, Disp::Pct, 76, false },
    {  19, "oscillators", "Oscillators", "", Quant::Count, Disp::Count, 1292, false },
    {  20, "portamento", "Portamento", "msec", Quant::Ms1k, Disp::Ms1k, 1300, false },
    {  21, "seed", "Seed", "", Quant::Real, Disp::Seed, 1360, false },
    {  22, "vl_atk_tm", "Vl Atk Tm", "msec", Quant::Real, Disp::Time, 196, true },
    {  23, "vl_atk_lv", "Vl Atk Lv", "%", Quant::Real, Disp::Pct, 152, true },
    {  24, "vl_dec_tm", "Vl Dec Tm", "msec", Quant::Real, Disp::Time, 200, true },
    {  25, "vl_dec_lv", "Vl Dec Lv", "%", Quant::Real, Disp::Pct, 188, true },
    {  26, "vl_rel_tm", "Vl Rel Tm", "msec", Quant::Real, Disp::Time, 204, true },
    {  27, "pt_env_rg", "Pt Env Rg", "s/tone", Quant::Semi, Disp::Semi, 316, false },
    {  28, "pt_ini_lv", "Pt Ini Lv", "%", Quant::Real, Disp::Pct, 256, true },
    {  29, "pt_atk_tm", "Pt Atk Tm", "msec", Quant::Real, Disp::Time, 304, true },
    {  30, "pt_atk_lv", "Pt Atk Lv", "%", Quant::Real, Disp::Pct, 260, true },
    {  31, "pt_dec_tm", "Pt Dec Tm", "msec", Quant::Real, Disp::Time, 308, true },
    {  32, "pt_dec_lv", "Pt Dec Lv", "%", Quant::Real, Disp::Pct, 296, true },
    {  33, "pt_rel_tm", "Pt Rel Tm", "msec", Quant::Real, Disp::Time, 312, true },
    {  34, "pt_rel_lv", "Pt Rel Lv", "%", Quant::Real, Disp::Pct, 300, true },
    {  35, "pn_env_rg", "Pn Env Rg", "%", Quant::Pct, Disp::Pct, 424, false },
    {  36, "pn_ini_lv", "Pn Ini Lv", "%", Quant::Real, Disp::Pct, 364, true },
    {  37, "pn_atk_tm", "Pn Atk Tm", "msec", Quant::Real, Disp::Time, 412, true },
    {  38, "pn_atk_lv", "Pn Atk Lv", "%", Quant::Real, Disp::Pct, 368, true },
    {  39, "pn_dec_tm", "Pn Dec Tm", "msec", Quant::Real, Disp::Time, 416, true },
    {  40, "pn_dec_lv", "Pn Dec Lv", "%", Quant::Real, Disp::Pct, 404, true },
    {  41, "pn_rel_tm", "Pn Rel Tm", "msec", Quant::Real, Disp::Time, 420, true },
    {  42, "pn_rel_lv", "Pn Rel Lv", "%", Quant::Real, Disp::Pct, 408, true },
    {  43, "rs_env_rg", "Rs Env Rg", "%", Quant::Pct50, Disp::Pct50, 532, false },
    {  44, "rs_ini_lv", "Rs Ini Lv", "%", Quant::Real, Disp::Pct, 472, true },
    {  45, "rs_atk_tm", "Rs Atk Tm", "msec", Quant::Real, Disp::Time, 520, true },
    {  46, "rs_atk_lv", "Rs Atk Lv", "%", Quant::Real, Disp::Pct, 476, true },
    {  47, "rs_dec_tm", "Rs Dec Tm", "msec", Quant::Real, Disp::Time, 524, true },
    {  48, "rs_dec_lv", "Rs Dec Lv", "%", Quant::Real, Disp::Pct, 512, true },
    {  49, "rs_rel_tm", "Rs Rel Tm", "msec", Quant::Real, Disp::Time, 528, true },
    {  50, "rs_rel_lv", "Rs Rel Lv", "%", Quant::Real, Disp::Pct, 516, true },
    {  51, "ns_env_rg", "Ns Env Rg", "%", Quant::Pct50, Disp::Pct50, 640, false },
    {  52, "ns_ini_lv", "Ns Ini Lv", "%", Quant::Real, Disp::Pct, 580, true },
    {  53, "ns_atk_tm", "Ns Atk Tm", "msec", Quant::Real, Disp::Time, 628, true },
    {  54, "ns_atk_lv", "Ns Atk Lv", "%", Quant::Real, Disp::Pct, 584, true },
    {  55, "ns_dec_tm", "Ns Dec Tm", "msec", Quant::Real, Disp::Time, 632, true },
    {  56, "ns_dec_lv", "Ns Dec Lv", "%", Quant::Real, Disp::Pct, 620, true },
    {  57, "ns_rel_tm", "Ns Rel Tm", "msec", Quant::Real, Disp::Time, 636, true },
    {  58, "ns_rel_lv", "Ns Rel Lv", "%", Quant::Real, Disp::Pct, 624, true },
    {  59, "vlvr_ini_lv", "VlVr Ini Lv", "%", Quant::Real, Disp::Pct, 688, true },
    {  60, "vlvr_atk_tm", "VlVr Atk Tm", "msec", Quant::Real, Disp::Time, 736, true },
    {  61, "vlvr_atk_lv", "VlVr Atk Lv", "%", Quant::Real, Disp::Pct, 692, true },
    {  62, "vlvr_dec_tm", "VlVr Dec Tm", "msec", Quant::Real, Disp::Time, 740, true },
    {  63, "vlvr_dec_lv", "VlVr Dec Lv", "%", Quant::Real, Disp::Pct, 728, true },
    {  64, "vlvr_rel_tm", "VlVr Rel Tm", "msec", Quant::Real, Disp::Time, 744, true },
    {  65, "vlvr_rel_lv", "VlVr Rel Lv", "%", Quant::Real, Disp::Pct, 732, true },
    {  66, "ptvr_ini_lv", "PtVr Ini Lv", "%", Quant::Real, Disp::Pct, 796, true },
    {  67, "ptvr_atk_tm", "PtVr Atk Tm", "msec", Quant::Real, Disp::Time, 844, true },
    {  68, "ptvr_atk_lv", "PtVr Atk Lv", "%", Quant::Real, Disp::Pct, 800, true },
    {  69, "ptvr_dec_tm", "PtVr Dec Tm", "msec", Quant::Real, Disp::Time, 848, true },
    {  70, "ptvr_dec_lv", "PtVr Dec Lv", "%", Quant::Real, Disp::Pct, 836, true },
    {  71, "ptvr_rel_tm", "PtVr Rel Tm", "msec", Quant::Real, Disp::Time, 852, true },
    {  72, "ptvr_rel_lv", "PtVr Rel Lv", "%", Quant::Real, Disp::Pct, 840, true },
    {  73, "pnvr_ini_lv", "PnVr Ini Lv", "%", Quant::Real, Disp::Pct, 904, true },
    {  74, "pnvr_atk_tm", "PnVr Atk Tm", "msec", Quant::Real, Disp::Time, 952, true },
    {  75, "pnvr_atk_lv", "PnVr Atk Lv", "%", Quant::Real, Disp::Pct, 908, true },
    {  76, "pnvr_dec_tm", "PnVr Dec Tm", "msec", Quant::Real, Disp::Time, 956, true },
    {  77, "pnvr_dec_lv", "PnVr Dec Lv", "%", Quant::Real, Disp::Pct, 944, true },
    {  78, "pnvr_rel_tm", "PnVr Rel Tm", "msec", Quant::Real, Disp::Time, 960, true },
    {  79, "pnvr_rel_lv", "PnVr Rel Lv", "%", Quant::Real, Disp::Pct, 948, true },
    {  80, "rsvr_ini_lv", "RsVr Ini Lv", "%", Quant::Real, Disp::Pct, 1012, true },
    {  81, "rsvr_atk_tm", "RsVr Atk Tm", "msec", Quant::Real, Disp::Time, 1060, true },
    {  82, "rsvr_atk_lv", "RsVr Atk Lv", "%", Quant::Real, Disp::Pct, 1016, true },
    {  83, "rsvr_dec_tm", "RsVr Dec Tm", "msec", Quant::Real, Disp::Time, 1064, true },
    {  84, "rsvr_dec_lv", "RsVr Dec Lv", "%", Quant::Real, Disp::Pct, 1052, true },
    {  85, "rsvr_rel_tm", "RsVr Rel Tm", "msec", Quant::Real, Disp::Time, 1068, true },
    {  86, "rsvr_rel_lv", "RsVr Rel Lv", "%", Quant::Real, Disp::Pct, 1056, true },
    {  87, "nsvr_ini_lv", "NsVr Ini Lv", "%", Quant::Real, Disp::Pct, 1120, true },
    {  88, "nsvr_atk_tm", "NsVr Atk Tm", "msec", Quant::Real, Disp::Time, 1168, true },
    {  89, "nsvr_atk_lv", "NsVr Atk Lv", "%", Quant::Real, Disp::Pct, 1124, true },
    {  90, "nsvr_dec_tm", "NsVr Dec Tm", "msec", Quant::Real, Disp::Time, 1172, true },
    {  91, "nsvr_dec_lv", "NsVr Dec Lv", "%", Quant::Real, Disp::Pct, 1160, true },
    {  92, "nsvr_rel_tm", "NsVr Rel Tm", "msec", Quant::Real, Disp::Time, 1176, true },
    {  93, "nsvr_rel_lv", "NsVr Rel Lv", "%", Quant::Real, Disp::Pct, 1164, true },
    {  94, "spd_ini_lv", "Spd Ini Lv", "%", Quant::Real, Disp::Pct, 1228, true },
    {  95, "spd_atk_tm", "Spd Atk Tm", "msec", Quant::Real, Disp::Time, 1276, true },
    {  96, "spd_atk_lv", "Spd Atk Lv", "%", Quant::Real, Disp::Pct, 1232, true },
    {  97, "spd_dec_tm", "Spd Dec Tm", "msec", Quant::Real, Disp::Time, 1280, true },
    {  98, "spd_dec_lv", "Spd Dec Lv", "%", Quant::Real, Disp::Pct, 1268, true },
    {  99, "spd_rel_tm", "Spd Rel Tm", "msec", Quant::Real, Disp::Time, 1284, true },
    { 100, "spd_rel_lv", "Spd Rel Lv", "%", Quant::Real, Disp::Pct, 1272, true },
};

// The quantiser the original applies to an incoming normalised value.
inline float quantise (Quant q, float v) {
    if (v < 0.0f) v = 0.0f; else if (v > 1.0f) v = 1.0f;
    switch (q) {
        case Quant::Pct:   return (float) (int) (v * 100.0f) / 100.0f;
        case Quant::Pan:   return ((float) (int) (v * 200.0f - 100.0f) + 100.0f) / 200.0f;
        case Quant::Count: return (float) (int) (v * 63.0f) / 63.0f;
        case Quant::Ms1k:  return (float) (int) (v * 999.0f) / 999.0f;
        case Quant::Semi:  return (float) (int) (v * 24.0f) / 24.0f;
        case Quant::Pct50: return (float) (int) (v * 50.0f) / 50.0f;
        case Quant::Real:  default: return v;
    }
}

// Envelope times: t_ms = 0.1 + 9999.9 * v^2  (fitted, max error 0.004 ms).
inline float envTimeMs (float v) { return 0.1f + 9999.9f * v * v; }
inline float envTimeNorm (float ms) { return ms <= 0.1f ? 0.0f : (float) __builtin_sqrt ((ms - 0.1) / 9999.9); }

} // namespace swarm
