"""Turn the measured parameter behaviour into a single machine-readable spec,
then emit the C++ header the JUCE plugin builds its parameters from.

Everything here comes from --map-params and the chunk differential; nothing is
guessed. See analysis/FINDINGS.md for how each law was established.
"""
import csv, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# quantiser laws, verified to zero error against the plugin's own readback
#   pct   : v' = floor(100v)/100          integer 0..100
#   pan   : n  = trunc(200v-100)          integer -100..100
#   count : v' = floor(63v)/63            integer 1..64  (Oscillators)
#   ms1k  : v' = floor(999v)/999          integer 1..1000 (Portamento)
#   semi  : v' = floor(24v)/24            integer 0..24
#   pct50 : v' = floor(50v)/50            integer 0..50
#   real  : stored as float, no quantisation
QUANT = {}
for i in range(0, 19): QUANT[i] = "pct"
QUANT[1] = "pan"
QUANT[19] = "count"; QUANT[20] = "ms1k"; QUANT[21] = "real"
QUANT[27] = "semi"; QUANT[35] = "pct"; QUANT[43] = "pct50"; QUANT[51] = "pct50"
for i in range(22, 101): QUANT.setdefault(i, "real")

# display law: how a normalised value reads out in engineering units
#   pct     0..100          lin     linear a*v+b        db     20*log10(v)
#   time    0.1 + 9999.9v^2 ms      count  1+63v        ms1k   1+999v
#   semi    0..24 s/tone            pct50  0..50 %      seed   v * 2^27
def display_law(idx, name, unit):
    if idx == 0:  return "db"
    if idx == 1:  return "pan"
    if idx == 19: return "count"
    if idx == 20: return "ms1k"
    if idx == 21: return "seed"
    if idx == 27: return "semi"
    if idx in (43, 51): return "pct50"
    if unit == "msec": return "time"
    return "pct"

rows = list(csv.DictReader(open(os.path.join(HERE, "data", "param_map.csv"))))
meta = {}
for r in rows:
    i = int(r["param_index"])
    meta.setdefault(i, (r["param_name"], r["unit"].strip()))

chunk = json.load(open(os.path.join(HERE, "data", "chunk_map.json")))
chunk["21"] = 1360   # seed; re-randomised per instance so the diff couldn't isolate it

# which of the five per-particle dimensions each param belongs to, and its role.
DIM = {0:"vol", 1:"pan", 2:"res", 3:"noise"}
VAR = {4:"vol", 5:"pitch", 6:"pan", 7:"res", 8:"noise"}
ENV_BLOCKS = [("vl","vol"),("pt","pitch"),("pn","pan"),("rs","res"),("ns","noise"),
              ("vlvr","vol_var"),("ptvr","pitch_var"),("pnvr","pan_var"),
              ("rsvr","res_var"),("nsvr","noise_var"),("spd","speed")]

spec = {"params": [], "envelopes": [b[1] for b in ENV_BLOCKS],
        "dimensions": ["vol","pitch","pan","res","noise"]}
for i in sorted(meta):
    name, unit = meta[i]
    spec["params"].append(dict(
        index=i, name=name, unit=unit,
        quant=QUANT[i], display=display_law(i, name, unit),
        chunk_offset=chunk.get(str(i)),
        chunk_type=("int32" if QUANT[i] != "real" or i == 21 else "float"),
    ))
json.dump(spec, open(os.path.join(HERE, "data", "spec.json"), "w"), indent=1)

# ---------------------------------------------------------------------------
# emit the C++ header
# ---------------------------------------------------------------------------
def ident(s):
    out = "".join(c if c.isalnum() else "_" for c in s)
    while "__" in out: out = out.replace("__", "_")
    return out.strip("_").lower()

hdr = ["// GENERATED by analysis/build_spec.py -- do not edit by hand.",
       "// Parameter table measured from the original SwarmSynth.dll: names and",
       "// units come from the plugin itself, the quantiser and display laws were",
       "// fitted to its own readback with zero residual error.",
       "#pragma once", "#include <cstdint>", "", "namespace swarm {", "",
       "enum class Quant { Pct, Pan, Count, Ms1k, Semi, Pct50, Real };",
       "enum class Disp  { Pct, Db, Pan, Count, Ms1k, Semi, Pct50, Time, Seed };",
       "", "struct ParamSpec {",
       "    int         index;", "    const char* id;", "    const char* name;",
       "    const char* unit;", "    Quant       quant;", "    Disp        disp;",
       "    int         chunkOffset;   // byte offset in an original .swarm chunk",
       "    bool        chunkIsFloat;",
       "};", "",
       "inline constexpr int kNumParams = %d;" % len(spec["params"]), "",
       "inline constexpr ParamSpec kParams[kNumParams] = {"]
Q = {"pct":"Quant::Pct","pan":"Quant::Pan","count":"Quant::Count","ms1k":"Quant::Ms1k",
     "semi":"Quant::Semi","pct50":"Quant::Pct50","real":"Quant::Real"}
D = {"pct":"Disp::Pct","db":"Disp::Db","pan":"Disp::Pan","count":"Disp::Count",
     "ms1k":"Disp::Ms1k","semi":"Disp::Semi","pct50":"Disp::Pct50","time":"Disp::Time",
     "seed":"Disp::Seed"}
for p in spec["params"]:
    hdr.append('    {{ {i:3d}, "{id}", "{nm}", "{un}", {q}, {d}, {off}, {isf} }},'.format(
        i=p["index"], id=ident(p["name"]), nm=p["name"], un=p["unit"],
        q=Q[p["quant"]], d=D[p["display"]],
        off=p["chunk_offset"] if p["chunk_offset"] is not None else -1,
        isf="true" if p["chunk_type"] == "float" else "false"))
hdr += ["};", "",
    "// The quantiser the original applies to an incoming normalised value. It",
    "// truncates rather than rounds -- verified against the plugin's own readback",
    "// with zero error across a 33-point sweep of every parameter.",
    "//",
    "// kGrip nudges the value away from zero before truncating. Without it a value",
    "// already on the grid but held as, say, 0.58999997 truncates to the step below,",
    "// so applying the quantiser twice walks the value downwards. The epsilon is a",
    "// ten-thousandth of a step, so the measured behaviour is unchanged.",
    "inline constexpr float kGrip = 1.0e-4f;",
    "",
    "inline float quantise (Quant q, float v) {",
    "    if (v < 0.0f) v = 0.0f; else if (v > 1.0f) v = 1.0f;",
    "    switch (q) {",
    "        case Quant::Pct:   return (float) (int) (v * 100.0f + kGrip) / 100.0f;",
    "        case Quant::Pan: {",
    "            // signed, and truncated toward zero, so the nudge has to go away",
    "            // from zero or negative values land a step too high",
    "            float x = v * 200.0f - 100.0f;",
    "            x += (x >= 0.0f ? kGrip : -kGrip);",
    "            return ((float) (int) x + 100.0f) / 200.0f;",
    "        }",
    "        case Quant::Count: return (float) (int) (v * 63.0f  + kGrip) / 63.0f;",
    "        case Quant::Ms1k:  return (float) (int) (v * 999.0f + kGrip) / 999.0f;",
    "        case Quant::Semi:  return (float) (int) (v * 24.0f  + kGrip) / 24.0f;",
    "        case Quant::Pct50: return (float) (int) (v * 50.0f  + kGrip) / 50.0f;",
    "        case Quant::Real:  default: return v;",
    "    }",
    "}", "",
    "// Envelope times: t_ms = 0.1 + 9999.9 * v^2  (fitted, max error 0.004 ms).",
    "inline float envTimeMs (float v) { return 0.1f + 9999.9f * v * v; }",
    "inline float envTimeNorm (float ms) { return ms <= 0.1f ? 0.0f : (float) __builtin_sqrt ((ms - 0.1) / 9999.9); }",
    "", "} // namespace swarm", ""]

out = os.path.join(ROOT, "juce", "Source", "SwarmParams.h")
os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write("\n".join(hdr))
print("wrote", out, "and analysis/data/spec.json")
